# Generated by Django 2.2.6 on 2019-10-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statapp', '0002_remove_population_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='population',
            name='nombre_hbitants',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
